### ISSUE TITLE
CSS minification in :not()

### ISSUE THREAD

**Issue by ShockedPlot7560** [nizarmah/auto-minify#27] opened 2022-02-08 17:10 UTC
Currently, all spaces in the :not() function are removed, breaking most conditions. Example: 
```css
ul > li:not(.class ul > li, .another-class ul > li) {
        display: none;
}
```
 will become : 
```css
ul>li:not(.classul>li,.another-classsul>li){display:none;}
```

**Comment by nizarmah** [comment] 2024-03-07 17:37
Oh. I never had that use case. 

Thanks for reporting it.
I'll make sure to address it.

I need some time, though. 
Ironic, saying it after 2 years. I know.

**Comment by nizarmah** [comment] 2024-03-19 17:18
Hey! Small update regarding this: the issue is with Clean CSS.

Lightning CSS was added as a new CSS engine in #36 .
It should resolve this issue.

I haven't created the release yet, but it'll resolve this issue.
I'll update the thread when I create the release, by the end of this week.

I'm not sure if Clean CSS will remain an option.
I'll try updating the package and see if they fixed it on their end.

**Comment by nizarmah** [comment] 2024-03-20 17:54
Hello again @ShockedPlot7560. Thanks again for reporting this btw! 

I've released `v3`, which contains the fix. I'm closing this. 

Don't hesitate to open a new issue if you run into any issues.
This time I assure you the response time will be much better 😅.

**Closed by nizarmah** 2024-03-20 17:54 UTC
